# Generated by Django 5.1.7 on 2025-05-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите заголовок",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите содержание статьи", verbose_name="Содержание"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Выберете изображение для превью",
                        null=True,
                        upload_to="blog/img",
                        verbose_name="Preview",
                    ),
                ),
                (
                    "create_data",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату создания",
                        null=True,
                        verbose_name="дата создания",
                    ),
                ),
                (
                    "is_publicated",
                    models.BooleanField(
                        default=True,
                        help_text="Укажите, опубликована статья ии нет",
                        verbose_name="Признак пуликации",
                    ),
                ),
                (
                    "number_shows",
                    models.IntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "книги",
                "ordering": ["title"],
            },
        ),
    ]
