# Generated by Django 5.1.7 on 2025-06-26 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Выберете изображение",
                null=True,
                upload_to="catalog/img",
                validators=[
                    django.core.validators.FileExtensionValidator(["jpeg", "PNG"])
                ],
                verbose_name="изображение",
            ),
        ),
    ]
